# Redirects from what the browser requests to what we serve
#https://github.com/am-innocenter/DataCuriousBlog/tree/master/content/post
#https://data-musings.netlify.app/

[[redirects]]
  from = "innocenter-amima.netlify.app/post/"
  to = "data-musings.netlify.app/"
  #https://github.com/am-innocenter/DataCuriousBlog/blob/master/content/post/cases.html
  #https://github.com/am-innocenter/Data-Statistics-Musings-with-Innocenter/tree/main/_site/posts
[[redirects]]
  from = "/cases/"
  to = "/posts/cases"
  #https://github.com/am-innocenter/DataCuriousBlog/blob/master/content/post/CensusKE.html
[[redirects]]
  from = "/censuske/"
  to = "/posts/censuske"


# Redirects from what the browser requests to what we serve
#[[redirects]]
 # from = "/post/"
  #to = "/"
#[[redirects]]
 # from = "/git-commit-wordcloud-rstats/"
  #to = "/posts/git-commit-wordcloud-rstats"
#[[redirects]]
 # from = "/using-r-to-remove-audiobooks-from-spotify/"
  #to = "/posts/using-r-to-remove-audiobooks-from-spotify"
